default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  adapter: postgresql
  database: blog_app_development
  username: admin
  password: Incorrect12*
  encoding: unicode
  host: localhost
  pool: 5

test:
  adapter: postgresql
  database: blog_app_test
  username: admin
  password: Incorrect12*
  encoding: unicode
  host: localhost
  pool: 5

production:
  <<: *default
  database: blog_app_production
  username: blog_app
  password: <%= ENV["BLOG_APP_DATABASE_PASSWORD"] %>
